# Generated by Django 4.1.4 on 2023-04-02 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BigIntegerField()),
                ('date', models.DateField()),
                ('picture_id', models.IntegerField(default=0)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupID', to='Group.group')),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('consum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to='buy.buy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID_cons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('added_by', models.IntegerField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyers', to='buy.buy')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID_buy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
