# Generated by Django 4.1.4 on 2023-04-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consum_contrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('contrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='buyer_contrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('contrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer')),
            ],
        ),
    ]
