# Generated by Django 4.1.4 on 2023-04-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_alter_buy_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.IntegerField(),
        ),
    ]
