# Generated by Django 4.1.4 on 2023-04-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_consum_contrib_buyer_contrib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='percent',
        ),
    ]
