# Generated by Django 4.1.7 on 2023-04-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture_id',
            field=models.IntegerField(default=0),
        ),
    ]
