# Generated by Django 4.1.7 on 2023-04-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='name',
        ),
    ]
